"""Add patient details to analysis

Revision ID: 50b97794421e
Revises: 75d17a33abfa
Create Date: 2026-08-16 03:41:45.928786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50b97794421e'
down_revision: Union[str, Sequence[str], None] = '75d17a33abfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('patient_age', sa.Integer(), nullable=True))
    op.add_column('analyses', sa.Column('patient_gender', sa.String(), nullable=True))
    op.add_column('analyses', sa.Column('clinical_notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'clinical_notes')
    op.drop_column('analyses', 'patient_gender')
    op.drop_column('analyses', 'patient_age')
    # ### end Alembic commands ###
