"""Add modality and clinical_suggestions

Revision ID: 75d17a33abfa
Revises: ea8a48de3896
Create Date: 2026-08-16 03:18:57.573498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75d17a33abfa'
down_revision: Union[str, Sequence[str], None] = 'ea8a48de3896'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('modality', sa.String(), server_default='chest-xray', nullable=False))
    op.add_column('analyses', sa.Column('clinical_suggestions', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'clinical_suggestions')
    op.drop_column('analyses', 'modality')
    # ### end Alembic commands ###
