"""Add review fields to Analysis

Revision ID: ea8a48de3896
Revises: ff30f165d1b1
Create Date: 2026-08-08 23:32:43.636270

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ea8a48de3896'
down_revision: str | Sequence[str] | None = 'ff30f165d1b1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('review_status', sa.String(), nullable=False))
    op.add_column('analyses', sa.Column('reviewer_id', sa.Uuid(), nullable=True))
    op.add_column('analyses', sa.Column('reviewer_notes', sa.String(), nullable=True))
    op.add_column('analyses', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_analyses_reviewer_id'), 'analyses', ['reviewer_id'], unique=False)
    op.create_foreign_key(None, 'analyses', 'users', ['reviewer_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'analyses', type_='foreignkey')  # type: ignore
    op.drop_index(op.f('ix_analyses_reviewer_id'), table_name='analyses')
    op.drop_column('analyses', 'reviewed_at')
    op.drop_column('analyses', 'reviewer_notes')
    op.drop_column('analyses', 'reviewer_id')
    op.drop_column('analyses', 'review_status')
    # ### end Alembic commands ###
